name: retroplayer
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  drawing_animation: ^0.1.3
  flutter_tts: 
  device_info: ^0.4.2+4
  gradient_text: ^1.0.2
  animate_do: ^1.7.2
  flutter_sound: ^4.0.4+1
  path_provider: ^1.6.11
  audioplayers: ^0.13.2
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/buttonPress.mp3

  fonts:
   - family: elixia
     fonts:
       - asset: assets/fonts/ELIXIA.ttf

   - family: blanka
     fonts:
       - asset: assets/fonts/Blanka.otf